### ISSUE TITLE
error collecting pyobjc-framework-cocoa

### ISSUE THREAD

**Issue by machina20** [ASebastian27/Reddit-Account-Generator#9]
after ``$ sudo pip install -r requirements.txt``:

```Collecting pyobjc-framework-Cocoa
  Downloading pyobjc-framework-Cocoa-9.1.1.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-60rcj3vw/pyobjc-framework-cocoa_af87fd24f58143c9adef8384a131b92a/setup.py", line 16, in <module>
          setup(
        File "/tmp/pip-install-60rcj3vw/pyobjc-framework-cocoa_af87fd24f58143c9adef8384a131b92a/pyobjc_setup.py", line 541, in setup
          os_level = get_os_level()
                     ^^^^^^^^^^^^^^
        File "/tmp/pip-install-60rcj3vw/pyobjc-framework-cocoa_af87fd24f58143c9adef8384a131b92a/pyobjc_setup.py", line 230, in get_os_level
          subprocess.check_output(["/usr/bin/sw_vers", "-productVersion"])
        File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib64/python3.11/subprocess.py", line 1917, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sw_vers'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It seems like pyeasygui is the one causing trouble because isntalling the other packages individually has no issues, but ``sudo pip install pyeasygui`` yields an identical error

**Comment by olivercas01** [comment]
Same here, any fixes yet?

**Comment by ghost** [comment]
in the requirement.txt, just remove the `pyeasygui` and it should work fine

**Comment by olivercas01** [comment]
It did, never thought of that, thank u so much

**Comment by ytcyde** [comment]
the .py file crashes if I don't have pyeasygui
